#!/usr/bin/env node
// Turn a Markdown document into an ordered list of blocks — prose rendered to
// HTML, and Fade code blocks — so a UI (e.g. a Svelte page) can render prose
// with {@html} and code with <fade-runnable>. Emits a JSON data module, which
// dodges all HTML/JSX/Svelte brace-escaping in generated markup.
//
// Runnability is OPT-IN via the fence info string (most doc snippets are
// fragments / intentionally-invalid / context-dependent and shouldn't auto-run):
//   ```basic            → display-only (highlighted, read-only, no diagnostics)
//   ```basic run        → interactive <fade-runnable> (Run + output)
//   ```basic run invalid→ interactive, keep diagnostics on (teach the error)
//
// Usage: fade-md-to-svelte <input.md> --out <output.js> [--title "…"]

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { marked } from 'marked';

const args = process.argv.slice(2);
const input = args.find((a) => !a.startsWith('--'));
const outIdx = args.indexOf('--out');
const out = outIdx !== -1 ? args[outIdx + 1] : null;
const titleIdx = args.indexOf('--title');
const title = titleIdx !== -1 ? args[titleIdx + 1] : null;

if (!input || !out) {
    console.error('usage: fade-md-to-svelte <input.md> --out <output.js> [--title "…"]');
    process.exit(1);
}

const src = readFileSync(resolve(input), 'utf8');
const tokens = marked.lexer(src);

const blocks = [];
let proseBuf = [];
const flushProse = () => {
    if (!proseBuf.length) return;
    blocks.push({ type: 'html', html: marked.parser(proseBuf) });
    proseBuf = [];
};

for (const tok of tokens) {
    const lang = (tok.type === 'code' ? (tok.lang || '') : '').trim().toLowerCase();
    const isFade = lang === 'basic' || lang.startsWith('basic ');
    if (isFade) {
        flushProse();
        const flags = lang.split(/\s+/).slice(1);
        blocks.push({
            type: 'code',
            code: tok.text,
            runnable: flags.includes('run'),
            invalid: flags.includes('invalid'),
        });
    } else {
        proseBuf.push(tok);
    }
}
flushProse();

const runnable = blocks.filter((b) => b.type === 'code' && b.runnable).length;
const display = blocks.filter((b) => b.type === 'code' && !b.runnable).length;

const banner = `// AUTO-GENERATED by @fadebasic/md-to-svelte from ${input}. Do not edit.\n`;
const payload = `${banner}export const HELP_TITLE = ${JSON.stringify(title)};\n`
    + `export const HELP_BLOCKS = ${JSON.stringify(blocks, null, 0)};\n`;

mkdirSync(dirname(resolve(out)), { recursive: true });
writeFileSync(resolve(out), payload);
console.log(`[md-to-svelte] ${input} → ${out}: ${blocks.length} blocks (${runnable} runnable, ${display} display-only)`);
